### ISSUE TITLE
lqmm fails with memory error for 30,904 row dataframe

### ISSUE THREAD

**Issue by tiburona** [marco-geraci/lqmm#1]
I have a large dataset (30.904) rows and I am trying to run this model `lqmm(std_brain ~ std_beh*type*taught, random = ~subject + run + cluster, group=subject/run/cluster, data = mydata, tau=.5)`. (I'm not at all sure I've specified it correctly, but that doesn't relate to my issue).  It failed on my local machine, and I tried provisioning an AWS instance with 96 gigs of RAM, which helpfully gave me the size of the vector it was trying to allocate: `Error: cannot allocate vector of size 147.3 Gb.` That tells me how much memory I need, so it should be possible to get an AWS instance to run it, but meanwhile, I filed a similar issue for `robustlmm` and the package author was able to rewrite so it was never necessary to load an nxn matrix into memory, and if it were possible for `lqmm` it would be wonderful for those of us with large datasets.  Thanks for your attention!

**Comment by marco-geraci** [comment]
For a simple model, that particular size of the dataset is not a problem at all. On the other hand, the incorrect specification of the model **does** relate to your issue. Please refer to lqmm documentation and vignette (https://doi.org/10.18637/jss.v057.i13). The 'group' argument requires the name of a single grouping variable; it does not support nesting (which is what it seems you're trying to do). Secondly, there is no need or reason to include the grouping variable into the formula for the random effects because the grouping variable _defines_ the random effect. Assuming those variables are factors, their inclusion in the 'random' argument triggers an explosion of quadrature knots and weights that lqmm tries to store before running estimation, hence the memory allocation error. For example, an acceptable model would be
`lqmm(std_brain ~ std_beh*type*taught, random = ~ 1, group=subject, data = mydata, tau=.5)`

I will close this issue but you can follow up via the maintainer's email address available at https://cran.r-project.org/package=lqmm.
